global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # Puedes agregar m√°s jobs si usas exporter de Minecraft
  # - job_name: "minecraft"
  #   static_configs:
  #     - targets: ["<IP>:<exporter_port>"]
